# Generated by Django 4.2.5 on 2023-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=124, unique=True, verbose_name='Активность'),
        ),
    ]
