# Generated by Django 4.2.5 on 2023-12-01 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_comment_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityforeventpost",
            options={"verbose_name_plural": "Активность - Мероприятие"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-id"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="eventpost",
            options={
                "ordering": ["-datetime"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteactivity",
            options={"verbose_name_plural": "Избранные активности пользователей"},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки"},
        ),
        migrations.AlterModelOptions(
            name="participation",
            options={"verbose_name_plural": "Мероприятие - Участник"},
        ),
    ]
