# Generated by Django 4.2.5 on 2023-12-05 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_favorite_favorite_unique_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoriteEvent',
        ),
    ]
