# Generated by Django 4.2.5 on 2023-12-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_favorite_favoriteevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteevent',
            options={'verbose_name_plural': 'Избранные мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': 'Участие в мероприятиях'},
        ),
    ]
