# Generated by Django 4.2.5 on 2023-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_activityforeventpost_options_and_more"),
        ("users", "0002_subscribe_subscribe_unique_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activity",
            field=models.ManyToManyField(
                related_name="user_activity", to="events.activity"
            ),
        ),
    ]
